name: sexdrugshelveticabold
favicon: null
layout_spectrum: 0.5383
typography_spectrum: 0.09344975813291967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dcd1b5'
    - '#383f37'
    - '#7a7871'
    - '#dc8e99'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
